from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
    url(r'^geneInfo/$', 'api.newapi.geneInfo'),
    url(r'^transcriptInfo/$', 'api.newapi.transcriptInfo'),
    url(r'^refSeqInfo/$', 'api.newapi.refSeqInfo'),    
    url(r'^getGeneDefaultTx/$', 'api.newapi.getGeneDefaultTx'),
    url(r'^snpInfo/$', 'api.newapi.snpInfo'),
    url(r'^snpFromDbSnp/$', 'api.newapi.snpFromDbSnp'),
    url(r'^ampliconInfo/$', 'api.newapi.ampliconInfo'),
    url(r'^probeInfo/$', 'api.newapi.probeInfo'),
    url(r'^rtpcrAmpliconInfo/$', 'api.newapi.rtpcrAmpliconInfo'),    
    url(r'^snpProbeInfo/$', 'api.newapi.snpProbeInfo'),
    url(r'^snpInProbe/$', 'api.newapi.snpInSnpProbe'),
    url(r'^alterationsInAmplicon/$', 'api.newapi.alterationsInAmplicon'),
    url(r'^refsetParameters/$', 'api.newapi.getRefsetParameters'),
    url(r'^refset/$', 'api.newapi.getRefset'),
    url(r'^createRefset/$', 'api.newapi.createRefset'),
    url(r'^createAnalysis/$', 'api.newapi.createAnalysis'),
    url(r'^deleteAnalysis/$', 'api.newapi.deleteAnalysis'),    
    url(r'^submitAnalysisResults/$', 'api.newapi.submitResults'),
    url(r'^experimentTypeInfo/$', 'api.newapi.experimentTypeInfo'),
    url(r'^allLabelTerms/$', 'api.newapi.allLabelTerms'),
    url(r'^genesInRegion/$', 'api.newapi.genesInRegion'),
    url(r'^transcriptsForGene/$', 'api.newapi.transcriptsForGene'),
    url(r'^predefinedGenomicLists/$', 'api.newapi.predefinedGenomicLists'),
    url(r'^newPredefinedGenomicList/$', 'api.newapi.newPredefinedGenomicList'),
    url(r'^deletePredefinedGenomicList/$', 'api.newapi.deletePredefinedGenomicList'),
    url(r'^getAmpliconTech/$', 'api.newapi.getAmpliconTech'),
    url(r'^sequenomPlates/$', 'api.newapi.sequenomPlates'),
    url(r'^searchReferences/$', 'api.newapi.searchReferences'),
    url(r'^deleteReferences/$', 'api.newapi.deleteReferences'),
    url(r'^checkAnnotUpdateStatus/$', 'api.newapi.checkAnnotUpdateStatus'),
    url(r'^updateAnnotations/$', 'api.newapi.updateAnnotations'),
)
